# Generated by Django 4.2 on 2023-06-07 10:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('DonationID', models.AutoField(primary_key=True, serialize=False)),
                ('is_perishable', models.BooleanField()),
                ('PickupTime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Photo', models.ImageField(upload_to='restaurant_photos/')),
                ('Location', models.CharField(max_length=255)),
                ('LicenseNumber', models.CharField(max_length=255)),
                ('HealthCertificateNumber', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='NonPerishableDonation',
            fields=[
                ('Donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='donor.donation')),
                ('MealTitle', models.CharField(max_length=255)),
                ('MealDescription', models.TextField()),
                ('MealPhotos', models.ImageField(upload_to='meal_photos_non_perishable/')),
                ('MealQuantityKgs', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('pickup_location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'non-perishable donation',
                'verbose_name_plural': 'non-perishable donations',
            },
        ),
        migrations.CreateModel(
            name='PerishableDonation',
            fields=[
                ('Donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='donor.donation')),
                ('MealType', models.CharField(max_length=255)),
                ('MealPhotos', models.ImageField(upload_to='meal_photos_perishable/')),
                ('MealQuantityPlates', models.PositiveIntegerField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'perishable donation',
                'verbose_name_plural': 'perishable donations',
            },
        ),
    ]
