# Generated by Django 4.2.2 on 2023-08-12 08:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import donor.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='PickupTime',
        ),
        migrations.AddField(
            model_name='donation',
            name='Status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('Intransit', 'Intransit')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='accepted_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipient.driver'),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='ngo_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_code',
            field=models.CharField(default='19456', max_length=5),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Status',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Verified', 'Verified')], default='Unverified', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='RestaurantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donor.restaurant'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nonperishabledonation',
            name='MealPhotos',
            field=models.ImageField(default=donor.models.default_nonperishable_meal_photo, upload_to='meal_photos_non_perishable/'),
        ),
        migrations.AlterField(
            model_name='perishabledonation',
            name='MealPhotos',
            field=models.ImageField(default=donor.models.default_perishable_meal_photo, upload_to='meal_photos_perishable/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ManagerID',
            field=models.ForeignKey(limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Photo',
            field=models.ImageField(default=donor.models.default_restaurant_photo, upload_to='restaurant_photos/'),
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_entity_type', models.CharField(choices=[('RESTAURANT', 'Restaurant')], max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)])),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.donation')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipient.organization')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantrating', to='donor.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
