# Generated by Django 4.2.2 on 2023-08-12 08:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_link',
            field=models.URLField(default='https://www.facebook.com'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_link',
            field=models.URLField(default='https://www.instagram.com'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default=users.models.default_profile_photo, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com'),
        ),
    ]
