# Generated by Django 4.2.2 on 2023-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_facebook_link_customuser_instagram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_token_created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_used',
        ),
        migrations.AddField(
            model_name='customuser',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
