# Generated by Django 4.2 on 2023-06-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipient', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='DriverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.driver'),
        ),
    ]
