# Generated by Django 4.2.2 on 2023-08-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0002_rename_phone_driver_phone_rename_photo_driver_photo_and_more'),
        ('driver', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='Destination',
            new_name='PickupPoint',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='PickupCode',
        ),
        migrations.AddField(
            model_name='delivery',
            name='ActualPickupDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='DistanceTraveled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='TimeSpentOnRoad',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='DeliveryID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipient.recipientdelivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('Intransit', 'Intransit')], default='pending', max_length=10),
        ),
    ]
