# Generated by Django 4.2 on 2023-06-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_delivery_distancetraveled_delivery_timespentonroad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='DistanceTraveled',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='TimeSpentOnRoad',
        ),
    ]
