# Generated by Django 4.2 on 2023-06-07 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('donor', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('DriverID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Status', models.CharField(choices=[('idle', 'idle'), ('onDelivery', 'onDelivery'), ('off-Work', 'off-Work')], default='idle', max_length=10)),
                ('Phone', models.CharField(max_length=255)),
                ('Photo', models.ImageField(upload_to='driver_photos/')),
                ('DriverIDNumber', models.CharField(max_length=255)),
                ('DrivingLicenseNumber', models.CharField(max_length=255)),
                ('CarNumberPlate', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'driver',
                'verbose_name_plural': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('OrganizationID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Photo', models.ImageField(upload_to='organization_photos/')),
                ('Location', models.CharField(max_length=255, unique=True)),
                ('LicenseNumber', models.CharField(max_length=255)),
                ('ManagerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='RecipientDelivery',
            fields=[
                ('DeliveryID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='driver.delivery')),
                ('Status', models.CharField(choices=[('future', 'future'), ('delivered', 'delivered'), ('intransit', 'intransit')], default='future', max_length=10)),
                ('PickupDateTime', models.DateTimeField()),
                ('Destination', models.ForeignKey(limit_choices_to={'Location__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='recipient.organization', to_field='Location')),
                ('DonationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donation')),
                ('DriverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.driver')),
            ],
            options={
                'verbose_name': 'recipient delivery',
                'verbose_name_plural': 'recipient deliveries',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='OrganizationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.organization'),
        ),
    ]
